### ISSUE TITLE
[git-gem] Fix failed tests

### ISSUE THREAD

**Issue by AlexKalinin** [alluviallabs/copy_git_history_as_empty_commits#9]
Currently, running tests on the ruby-git

    ./bin/test

    
Will show that one test is failed: 

```
.......................................................................................F
==============================================================================================================
Failure: test_commit_with_date(TestLib)
/Users/alexkalinin/prj/alluviallabs/_forks/ruby-git/tests/units/test_lib.rb:45:in `test_commit_with_date'
     42: 
     43:     data = @lib.commit_data('HEAD')
     44: 
  => 45:     assert_equal("Scott Chacon <schacon@gmail.com> #{author_date.strftime("%s %z")}", data['author'])
     46:   end
     47: 
     48:   def test_commit_with_no_verify
<"Scott Chacon <schacon@gmail.com> 1470256620 -0300"> expected but was
<"Alex Kalinin <login.hedin@gmail.com> 1470256620 -0300">

diff:
? Sc             ott Chacon <schacon@gmail.com> 1470256620 -0300
? Alex Kalinin <l gin. edi                                      
? ?? ???? ????????????                                      
==============================================================================================================
.....................................................................error: unsupported value for gpg.format: ssh
fatal: bad config variable 'gpg.format' in file '.git/config' at line 9
E
==============================================================================================================
Error: test_commit_data(TestSignedCommits):
  Git::GitExecuteError: git '--git-dir=/private/tmp/git_test1676012786237/.git' '--work-tree=/private/tmp/git_test1676012786237' '-c' 'core.quotePath=true' '-c' 'color.ui=false' cat-file 'commit' 'HEAD'  2>&1:fatal: Not a valid object name HEAD
/Users/alexkalinin/prj/alluviallabs/_forks/ruby-git/lib/git/lib.rb:1151:in `command'
/Users/alexkalinin/prj/alluviallabs/_forks/ruby-git/lib/git/lib.rb:1063:in `command_lines'
/Users/alexkalinin/prj/alluviallabs/_forks/ruby-git/lib/git/lib.rb:223:in `commit_data'
/Users/alexkalinin/prj/alluviallabs/_forks/ruby-git/tests/units/test_signed_commits.rb:30:in `block in test_commit_data'
     27:       `git add README.md`
     28:       `git commit -S -m "Signed, sealed, delivered"`
     29: 
  => 30:       data = Git.open('.').lib.commit_data('HEAD')
     31: 
     32:       assert_match(SSH_SIGNATURE_REGEXP, data['gpgsig'])
     33:       assert_equal("Signed, sealed, delivered\n", data['message'])
/Users/alexkalinin/prj/alluviallabs/_forks/ruby-git/tests/units/test_signed_commits.rb:20:in `block in in_repo_with_signing_config'
/Users/alexkalinin/prj/alluviallabs/_forks/ruby-git/tests/test_helper.rb:62:in `block in in_temp_dir'
/Users/alexkalinin/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/fileutils.rb:244:in `chdir'
/Users/alexkalinin/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/fileutils.rb:244:in `cd'
/Users/alexkalinin/prj/alluviallabs/_forks/ruby-git/tests/test_helper.rb:61:in `in_temp_dir'
/Users/alexkalinin/prj/alluviallabs/_forks/ruby-git/tests/units/test_signed_commits.rb:14:in `in_repo_with_signing_config'
/Users/alexkalinin/prj/alluviallabs/_forks/ruby-git/tests/units/test_signed_commits.rb:25:in `test_commit_data'
==============================================================================================================
.........................
Finished in 68.066965 seconds.
--------------------------------------------------------------------------------------------------------------
183 tests, 666 assertions, 1 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
98.9071% passed
--------------------------------------------------------------------------------------------------------------
2.69 tests/s, 9.78 assertions/s

```

**Comment by Asculapa** [comment]
I ran `/bin/test` and got slightly different errors:  
```
Loaded suite ./bin/test
Started
..............................................................................E
===============================================================================================================================================================================================================================
Error: test_git_init_initial_branch(TestInit):
  Git::GitExecuteError: git '--git-dir=/tmp/git_test1676060011047/.git' '--work-tree=/tmp/git_test1676060011047' '-c' 'core.quotePath=true' '-c' 'color.ui=false' init '--initial-branch=main'  2>&1:error: unknown option `initial-branch=main'
  usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]
  
      --template <template-directory>
                            directory from which templates will be used
      --bare                create a bare repository
      --shared[=<permissions>]
                            specify that the git repository is to be shared amongst several users
      -q, --quiet           be quiet
      --separate-git-dir <gitdir>
                            separate git dir from working tree
  
/home/asculapa/prj/ruby-git/lib/git/lib.rb:1151:in `command'
/home/asculapa/prj/ruby-git/lib/git/lib.rb:80:in `init'
/home/asculapa/prj/ruby-git/lib/git/base.rb:55:in `init'
/home/asculapa/prj/ruby-git/lib/git.rb:259:in `init'
/home/asculapa/prj/ruby-git/tests/units/test_init.rb:68:in `block in test_git_init_initial_branch'
     65: 
     66:   def test_git_init_initial_branch
     67:     in_temp_dir do |path|
  => 68:       repo = Git.init(path, initial_branch: 'main')
     69:       assert(File.directory?(File.join(path, '.git')))
     70:       assert(File.exist?(File.join(path, '.git', 'config')))
     71:       assert_equal('false', repo.config('core.bare'))
/home/asculapa/prj/ruby-git/tests/test_helper.rb:62:in `block in in_temp_dir'
/usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:139:in `chdir'
/usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:139:in `cd'
/home/asculapa/prj/ruby-git/tests/test_helper.rb:61:in `in_temp_dir'
/home/asculapa/prj/ruby-git/tests/units/test_init.rb:67:in `test_git_init_initial_branch'
===============================================================================================================================================================================================================================
..............................................................................error: unsupported value for gpg.format: ssh
fatal: bad config variable 'gpg.format' in file '.git/config' at line 7
E
===============================================================================================================================================================================================================================
Error: test_commit_data(TestSignedCommits):
  Git::GitExecuteError: git '--git-dir=/tmp/git_test1676060018239/.git' '--work-tree=/tmp/git_test1676060018239' '-c' 'core.quotePath=true' '-c' 'color.ui=false' cat-file 'commit' 'HEAD'  2>&1:fatal: Not a valid object name HEAD
/home/asculapa/prj/ruby-git/lib/git/lib.rb:1151:in `command'
/home/asculapa/prj/ruby-git/lib/git/lib.rb:1063:in `command_lines'
/home/asculapa/prj/ruby-git/lib/git/lib.rb:223:in `commit_data'
/home/asculapa/prj/ruby-git/tests/units/test_signed_commits.rb:30:in `block in test_commit_data'
     27:       `git add README.md`
     28:       `git commit -S -m "Signed, sealed, delivered"`
     29: 
  => 30:       data = Git.open('.').lib.commit_data('HEAD')
     31: 
     32:       assert_match(SSH_SIGNATURE_REGEXP, data['gpgsig'])
     33:       assert_equal("Signed, sealed, delivered\n", data['message'])
/home/asculapa/prj/ruby-git/tests/units/test_signed_commits.rb:20:in `block in in_repo_with_signing_config'
/home/asculapa/prj/ruby-git/tests/test_helper.rb:62:in `block in in_temp_dir'
/usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:139:in `chdir'
/usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:139:in `cd'
/home/asculapa/prj/ruby-git/tests/test_helper.rb:61:in `in_temp_dir'
/home/asculapa/prj/ruby-git/tests/units/test_signed_commits.rb:14:in `in_repo_with_signing_config'
/home/asculapa/prj/ruby-git/tests/units/test_signed_commits.rb:25:in `test_commit_data'
===============================================================================================================================================================================================================================
.........................
Finished in 15.107680489 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
183 tests, 662 assertions, 0 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
98.9071% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
12.11 tests/s, 43.82 assertions/s

```
However, I also have  `error: unsupported value for gpg.format: ssh`. This is because you have `git < 2.34`, which does not have SSH signing.  
Try checking the git version and update if necessary::
```
$ git --version
git version 2.25.1

//for ubuntu

$ sudo add-apt-repository ppa:git-core/ppa -y
$ sudo apt-get update
$ sudo apt-get upgrade
```

**Comment by Asculapa** [comment]
After updating my git version to 2.39.1:

```
$ ./bin/test 
Loaded suite ./bin/test
Started
.......................................................................................................................................................................................
Finished in 15.681780589 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
183 tests, 668 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
11.67 tests/s, 42.60 assertions/s


```

**Comment by AlexKalinin** [comment]
My git-version is:

```
git --version
git version 2.30.1 (Apple Git-130)
```


Maybe it's because I work on a Mac, and not on linux... 

Ok, I will look it myself later. Thanks)
